#include "keycodes_de.h"

int convertChar(char c){
  switch(c){
    case ' ': return 32;
    case '!': return 33;
    case 'Ä': return 34;
    case '§': return 35;
    case '$': return 36;
    case '%': return 37;
    case '/': return 38;
    case 'ä': return 39;
    case ')': return 40;
    case '=': return 41;
    case '(': return 42;
    case '`': return 43;
    case ',': return 44;
    case 'ß': return 45;
    case '.': return 46;
    case '-': return 47;
    case '0': return 48;
    case '1': return 49;
    case '2': return 50;
    case '3': return 51;
    case '4': return 52;
    case '5': return 53;
    case '6': return 54;
    case '7': return 55;
    case '8': return 56;
    case '9': return 57;
    case 'Ö': return 58;
    case 'ö': return 59;
    case ';': return 60;
    case '´': return 61;
    case ':': return 62;
    case '_': return 63;
    case '"': return 64;
    case 'A': return 65;
    case 'B': return 66;
    case 'C': return 67;
    case 'D': return 68;
    case 'E': return 69;
    case 'F': return 70;
    case 'G': return 71;
    case 'H': return 72;
    case 'I': return 73;
    case 'J': return 74;
    case 'K': return 75;
    case 'L': return 76;
    case 'M': return 77;
    case 'N': return 78;
    case 'O': return 79;
    case 'P': return 80;
    case 'Q': return 81;
    case 'R': return 82;
    case 'S': return 83;
    case 'T': return 84;
    case 'U': return 85;
    case 'V': return 86;
    case 'W': return 87;
    case 'X': return 88;
    case 'Z': return 89;
    case 'Y': return 90;
    case 'ü': return 91;
    case '#': return 92;
    case '+': return 93;
    case '&': return 94;
    case '?': return 95;
    case '^': return 96;
    case 'a': return 97;
    case 'b': return 98;
    case 'c': return 99;
    case 'd': return 100;
    case 'e': return 101;
    case 'f': return 102;
    case 'g': return 103;
    case 'h': return 104;
    case 'i': return 105;
    case 'j': return 106;
    case 'k': return 107;
    case 'l': return 108;
    case 'm': return 109;
    case 'n': return 110;
    case 'o': return 111;
    case 'p': return 112;
    case 'q': return 113;
    case 'r': return 114;
    case 's': return 115;
    case 't': return 116;
    case 'u': return 117;
    case 'v': return 118;
    case 'w': return 119;
    case 'x': return 120;
    case 'z': return 121;
    case 'y': return 122;
    case 'Ü': return 123;
    case '\'': return 124;
    case '*': return 125;
    case '°': return 126;
    //case 'a': return 140;
    //case 'b': return 141;
    //case 'c': return 142;
    //case 'd': return 143;
    //case 'e': return 144;
    //case 'f': return 145;
    //case 'g': return 146;
    //case 'h': return 147;
    //case 'i': return 148;
    //case 'j': return 149;
    //case 'k': return 150;
    //case 'l': return 151;
    //case 'm': return 152;
    //case 'n': return 153;
    //case 'o': return 154;
    //case 'p': return 155;
    //case 'q': return 156;
    //case 'r': return 157;
    //case 's': return 158;
    //case 't': return 159;
    //case 'u': return 160;
    //case 'v': return 161;
    //case 'w': return 162;
    //case 'x': return 163;
    //case 'z': return 164;
    //case 'y': return 165;
    //case '1': return 166;
    //case '2': return 167;
    //case '3': return 168;
    //case '4': return 169;
    //case '5': return 170;
    //case '6': return 171;
    //case '7': return 172;
    //case '8': return 173;
    //case '9': return 174;
    //case '0': return 175;
    //case ' ': return 180;
    //case 'ß': return 181;
    //case '´': return 182;
    //case 'ü': return 183;
    //case '+': return 184;
    //case '#': return 185;
    //case '#': return 186;
    //case 'ö': return 187;
    //case 'ä': return 188;
    //case '^': return 189;
    //case ',': return 190;
    //case '.': return 191;
    //case '-': return 192;
  }
  
}

void sendInput(String input){
  for(int i = 0; i < input.length(); i++){
    Keyboard.press(convertChar(input.charAt(i)));
    //delay(10);
    Keyboard.releaseAll();
  }
}

